name: Run run Try.py Every 5 Minutes

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
          

      - name: Run try.py
        run: python try.py
      - name: Debug Info
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory: $(ls)"
          echo "Path to Python: $(which python)"
